# Generated by Django 3.0.5 on 2020-04-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='game_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
