# Generated by Django 3.0.5 on 2020-04-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_gamescore_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='first_team_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_team', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='second_team_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_team', to='teams.Team'),
        ),
    ]
