# Generated by Django 3.0.5 on 2020-04-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200430_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='second_team',
        ),
    ]
